Repository openworm/openworm_docs, pull requests merged in 2019-10, with the labels that each got.

#57 basic Circle-CI build
  .circleci/config.yml
  README.md
Labels: enhancement

#52 Update background.md
  docs/background.md
Labels: in progress

#59 remove redundant old site
  old/Community/github.rst
  old/Community/membership.rst
  old/Community/repositories.rst
  old/Makefile
  old/Projects/Movement/Data/MRC_HDF5.md
  old/Projects/Movement/Data/MRC_HDF5.rst
  old/Projects/Movement/Data/MRC_HDF5/definitions.md
  old/Projects/Movement/Data/MRC_HDF5/definitions.rst
  old/Projects/Movement/Data/MRC_HDF5/ftp_structure.md
  old/Projects/Movement/Data/MRC_HDF5/ftp_structure.rst
  old/Projects/Movement/Data/MRC_HDF5/info_structure_documentation.md
  old/Projects/Movement/Data/MRC_HDF5/info_structure_documentation.rst
  old/Projects/Movement/Data/MRC_HDF5/worm_structure_documentation.md
  old/Projects/Movement/Data/MRC_HDF5/worm_structure_documentation.rst
  old/Projects/Movement/Data/ReadMe.md
  old/Projects/Movement/Data/worm_movement_data.rst
  old/Projects/Movement/ProgressReport_2013_09_04.md
  old/Projects/Movement/ProgressReport_2013_09_04.rst
  old/Projects/Movement/ReadMe.md
  old/Projects/Movement/features.md
  old/Projects/Movement/features.rst
  old/Projects/Movement/features/nmeth.2560-S3.csv
  old/Projects/community-proj.rst
  old/Projects/datarep.rst
  old/Projects/geppetto.rst
  old/Projects/muscle-neuron-integration.rst
  old/Projects/optimization.rst
  old/Projects/sibernetic.rst
  old/Projects/worm-movement.rst
  old/Resources/running-nc.rst
  old/background.rst
  old/community.rst
  old/conf.py
  old/faq.rst
  old/fullhistory.rst
  old/index.rst
  old/intro.rst
  old/make.bat
  old/modeling.rst
  old/projects.rst
  old/releases.rst
  old/resources.rst
  rst-to-md-conversion/README.md
  rst-to-md-conversion/convert.sh
Labels: ready
